<a href="https://colab.research.google.com/github/nomo82/python/blob/main/6_lambda.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#En este caso mezclaremos la funcioan lambda con el método apply
#La función lambda en python es una forma de escribir funciones menos robustas
import pandas as pd
import numpy as np

In [ ]:
#Conectar a Google Drive
from google.colab import drive
drive.mount('/content/drive')

In [ ]:
#Traemos el mismo archivo
df_jugadores=pd.read_csv('/content/drive/MyDrive/Alexander Niño.lnk/2025/_Python/players_20.csv')
#Le defino el index
df_jugadores.set_index('short_name', inplace=True)
#Selecciono las columnas que voy a usar
df_jugadores= df_jugadores[['player_url','long_name', 'age',  'dob',  'height_cm',  'weight_kg',  'nationality',  'club']]
df_jugadores.head(5)

,player_url,long_name,age,dob,height_cm,weight_kg,nationality,club
short_name,,,,,,,,
L. Messi,https://sofifa.com/player/158023/lionel-messi/...,Lionel Andrés Messi Cuccittini,32,1987-06-24,170,72,Argentina,FC Barcelona
Cristiano Ronaldo,https://sofifa.com/player/20801/c-ronaldo-dos-...,Cristiano Ronaldo dos Santos Aveiro,34,1985-02-05,187,83,Portugal,Juventus
Neymar Jr,https://sofifa.com/player/190871/neymar-da-sil...,Neymar da Silva Santos Junior,27,1992-02-05,175,68,Brazil,Paris Saint-Germain
J. Oblak,https://sofifa.com/player/200389/jan-oblak/20/...,Jan Oblak,26,1993-01-07,188,87,Slovenia,Atlético Madrid
E. Hazard,https://sofifa.com/player/183277/eden-hazard/2...,Eden Hazard,28,1991-01-07,175,74,Belgium,Real Madrid

In [ ]:
#Las funciones normalmente se ven de la siguiente manera
def sumar(a, b):
  x=a+b
  return (x)

In [ ]:
sumar(29,24)

53

In [ ]:
from binascii import b2a_base64
def modulo(a,b):
  y=a%b
  return (y)

In [ ]:
modulo(25,2)

1

In [ ]:
#Vamos a ver como se hace las funciones usando lambda
#Primero se asigna el nombre luego asignamos el valor, luego introducimos los parametros, luego dos puntos y por ultimo el output
sumar_2=lambda a,b: a+b

In [ ]:
sumar_2(39,39)

78

In [ ]:
modulo_2=lambda a,b: a%b

In [ ]:
modulo_2(48,2)

0

In [ ]:
df_jugadores.head(3)

,player_url,long_name,age,dob,height_cm,weight_kg,nationality,club
short_name,,,,,,,,
L. Messi,https://sofifa.com/player/158023/lionel-messi/...,Lionel Andrés Messi Cuccittini,32,1987-06-24,170,72,Argentina,FC Barcelona
Cristiano Ronaldo,https://sofifa.com/player/20801/c-ronaldo-dos-...,Cristiano Ronaldo dos Santos Aveiro,34,1985-02-05,187,83,Portugal,Juventus
Neymar Jr,https://sofifa.com/player/190871/neymar-da-sil...,Neymar da Silva Santos Junior,27,1992-02-05,175,68,Brazil,Paris Saint-Germain

In [ ]:
#Ahora usemos a apply con lamba
#Vamosa a pasar los cm a mtros en la información de los jugadores
#En este caso si usamos apply no necesitamos poner el nombre de la función
df_jugadores['height_cm'].apply(lambda x:x/100)

short_name
L. Messi             1.70
Cristiano Ronaldo    1.87
Neymar Jr            1.75
J. Oblak             1.88
E. Hazard            1.75
                     ...
Shao Shuai           1.86
Xiao Mingjie         1.77
Zhang Wei            1.86
Wang Haijian         1.85
Pan Ximing           1.82
Name: height_cm, Length: 18278, dtype: float64

In [ ]:
df_jugadores['age'].apply(lambda x:x*12)

short_name
L. Messi             384
Cristiano Ronaldo    408
Neymar Jr            324
J. Oblak             312
E. Hazard            336
                    ...
Shao Shuai           264
Xiao Mingjie         264
Zhang Wei            228
Wang Haijian         216
Pan Ximing           312
Name: age, Length: 18278, dtype: int64

In [ ]:
#Para convertir los cm a metros
df_jugadores['height_cm']/100

short_name
L. Messi             1.70
Cristiano Ronaldo    1.87
Neymar Jr            1.75
J. Oblak             1.88
E. Hazard            1.75
                     ...
Shao Shuai           1.86
Xiao Mingjie         1.77
Zhang Wei            1.86
Wang Haijian         1.85
Pan Ximing           1.82
Name: height_cm, Length: 18278, dtype: float64

In [ ]:
#Tambien podemos pasar los nombre de los jugadores a mayusculas
df_jugadores['long_name'].apply(lambda x:x.upper())

short_name
L. Messi                  LIONEL ANDRÉS MESSI CUCCITTINI
Cristiano Ronaldo    CRISTIANO RONALDO DOS SANTOS AVEIRO
Neymar Jr                  NEYMAR DA SILVA SANTOS JUNIOR
J. Oblak                                       JAN OBLAK
E. Hazard                                    EDEN HAZARD
                                    ...
Shao Shuai                                            邵帅
Xiao Mingjie                                MINGJIE XIAO
Zhang Wei                                             张威
Wang Haijian                                         汪海健
Pan Ximing                                           潘喜明
Name: long_name, Length: 18278, dtype: object

In [ ]:
#Si quiero hacerlo simple pero con mas memoria sería asi
df_jugadores['long_name'].str.upper()

short_name
L. Messi                  LIONEL ANDRÉS MESSI CUCCITTINI
Cristiano Ronaldo    CRISTIANO RONALDO DOS SANTOS AVEIRO
Neymar Jr                  NEYMAR DA SILVA SANTOS JUNIOR
J. Oblak                                       JAN OBLAK
E. Hazard                                    EDEN HAZARD
                                    ...
Shao Shuai                                            邵帅
Xiao Mingjie                                MINGJIE XIAO
Zhang Wei                                             张威
Wang Haijian                                         汪海健
Pan Ximing                                           潘喜明
Name: long_name, Length: 18278, dtype: object

In [ ]:
#Tambien puedo usar lambda para extraer partes de fechas
#Primero debemos garantizar que la columna fecha este en modo date
df_jugadores['dob']=pd.to_datetime(df_jugadores['dob'])

In [ ]:
#ahora extraemos los años solo con la funcion lambda
df_jugadores['dob'].apply(lambda x:x.year)

short_name
L. Messi             1987
Cristiano Ronaldo    1985
Neymar Jr            1992
J. Oblak             1993
E. Hazard            1991
                     ...
Shao Shuai           1997
Xiao Mingjie         1997
Zhang Wei            2000
Wang Haijian         2000
Pan Ximing           1993
Name: dob, Length: 18278, dtype: int64

In [ ]:
df_jugadores['dob'].apply(lambda x:x.month_name())

short_name
L. Messi                 June
Cristiano Ronaldo    February
Neymar Jr            February
J. Oblak              January
E. Hazard             January
                       ...
Shao Shuai              March
Xiao Mingjie          January
Zhang Wei                 May
Wang Haijian           August
Pan Ximing            January
Name: dob, Length: 18278, dtype: object

In [ ]:
df_jugadores['IMC'] = df_jugadores.apply(lambda x: x['weight_kg'] / ((x['height_cm'] / 100) ** 2), axis=1)

In [ ]:
df_jugadores.head(3)

,player_url,long_name,age,dob,height_cm,weight_kg,nationality,club,IMC
short_name,,,,,,,,,
L. Messi,https://sofifa.com/player/158023/lionel-messi/...,Lionel Andrés Messi Cuccittini,32,1987-06-24,170,72,Argentina,FC Barcelona,24.913495
Cristiano Ronaldo,https://sofifa.com/player/20801/c-ronaldo-dos-...,Cristiano Ronaldo dos Santos Aveiro,34,1985-02-05,187,83,Portugal,Juventus,23.735308
Neymar Jr,https://sofifa.com/player/190871/neymar-da-sil...,Neymar da Silva Santos Junior,27,1992-02-05,175,68,Brazil,Paris Saint-Germain,22.204082