<a href="https://colab.research.google.com/github/nomo82/python/blob/main/Taller_Filtros.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
from google.colab import drive
drive.mount('/content/drive')
import pandas as pd
import numpy as np
#PRIMERA PARTE
#Traigo y convierto el dataframe
df_computadores=pd.read_csv('/content/drive/MyDrive/CURSOS/Colab Notebooks/Python_2/laptop_price (2).csv', encoding='ISO-8859-1')
df_computadores.head(5)

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

,laptop_ID,Company,Product,TypeName,Inches,ScreenResolution,Cpu,Ram,Memory,Gpu,OpSys,Weight,Price_euros
0,1,Apple,MacBook Pro,Ultrabook,13.3,IPS Panel Retina Display 2560x1600,Intel Core i5 2.3GHz,8GB,128GB SSD,Intel Iris Plus Graphics 640,macOS,1.37kg,1339.69
1,2,Apple,Macbook Air,Ultrabook,13.3,1440x900,Intel Core i5 1.8GHz,8GB,128GB Flash Storage,Intel HD Graphics 6000,macOS,1.34kg,898.94
2,3,HP,250 G6,Notebook,15.6,Full HD 1920x1080,Intel Core i5 7200U 2.5GHz,8GB,256GB SSD,Intel HD Graphics 620,No OS,1.86kg,575.00
3,4,Apple,MacBook Pro,Ultrabook,15.4,IPS Panel Retina Display 2880x1800,Intel Core i7 2.7GHz,16GB,512GB SSD,AMD Radeon Pro 455,macOS,1.83kg,2537.45
4,5,Apple,MacBook Pro,Ultrabook,13.3,IPS Panel Retina Display 2560x1600,Intel Core i5 3.1GHz,8GB,256GB SSD,Intel Iris Plus Graphics 650,macOS,1.37kg,1803.60

In [ ]:
df_computadores[df_computadores['Company']!='HP'].value_counts('Company')

Company
Lenovo       297
Dell         297
Asus         158
Acer         103
MSI           54
Toshiba       48
Apple         21
Samsung        9
Mediacom       7
Razer          7
Microsoft      6
Vero           4
Xiaomi         4
Chuwi          3
Fujitsu        3
Google         3
LG             3
Huawei         2
Name: count, dtype: int64

In [ ]:
df_computadores[df_computadores['Price_euros']>2000].value_counts('Price_euros')

Price_euros
2299.00    6
2499.00    5
2449.00    4
2099.00    4
2799.00    4
          ..
2277.00    1
2267.86    1
2254.00    1
2250.68    1
6099.00    1
Name: count, Length: 108, dtype: int64

In [ ]:
df_computadores['Tamaño']= np.where(df_computadores['Inches']>15, 'Grande','Pequeña')
df_computadores.head(5)

,laptop_ID,Company,Product,TypeName,Inches,ScreenResolution,Cpu,Ram,Memory,Gpu,OpSys,Weight,Price_euros,Tamaño
0,1,Apple,MacBook Pro,Ultrabook,13.3,IPS Panel Retina Display 2560x1600,Intel Core i5 2.3GHz,8GB,128GB SSD,Intel Iris Plus Graphics 640,macOS,1.37kg,1339.69,Pequeña
1,2,Apple,Macbook Air,Ultrabook,13.3,1440x900,Intel Core i5 1.8GHz,8GB,128GB Flash Storage,Intel HD Graphics 6000,macOS,1.34kg,898.94,Pequeña
2,3,HP,250 G6,Notebook,15.6,Full HD 1920x1080,Intel Core i5 7200U 2.5GHz,8GB,256GB SSD,Intel HD Graphics 620,No OS,1.86kg,575.00,Grande
3,4,Apple,MacBook Pro,Ultrabook,15.4,IPS Panel Retina Display 2880x1800,Intel Core i7 2.7GHz,16GB,512GB SSD,AMD Radeon Pro 455,macOS,1.83kg,2537.45,Grande
4,5,Apple,MacBook Pro,Ultrabook,13.3,IPS Panel Retina Display 2560x1600,Intel Core i5 3.1GHz,8GB,256GB SSD,Intel Iris Plus Graphics 650,macOS,1.37kg,1803.60,Pequeña

In [ ]:
df_computadores.value_counts('Tamaño')

Tamaño
Grande     835
Pequeña    468
Name: count, dtype: int64

In [ ]:
condiciones_1=[
    df_computadores['Inches']>15,
    (df_computadores['Inches']> 13) & (df_computadores['Inches']<=15),
    (df_computadores['Inches']>10) & (df_computadores['Inches']<= 13),
    df_computadores['Inches']<= 10
]

valores_1=['Grande', 'Mediana', 'Pequeña', 'Muy Pequeña']
df_computadores['Medida Pantalla']= np.select(condiciones_1, valores_1)
df_computadores

,laptop_ID,Company,Product,TypeName,Inches,ScreenResolution,Cpu,Ram,Memory,Gpu,OpSys,Weight,Price_euros,Tamaño,Medida Pantalla
0,1,Apple,MacBook Pro,Ultrabook,13.3,IPS Panel Retina Display 2560x1600,Intel Core i5 2.3GHz,8GB,128GB SSD,Intel Iris Plus Graphics 640,macOS,1.37kg,1339.69,Pequeña,Mediana
1,2,Apple,Macbook Air,Ultrabook,13.3,1440x900,Intel Core i5 1.8GHz,8GB,128GB Flash Storage,Intel HD Graphics 6000,macOS,1.34kg,898.94,Pequeña,Mediana
2,3,HP,250 G6,Notebook,15.6,Full HD 1920x1080,Intel Core i5 7200U 2.5GHz,8GB,256GB SSD,Intel HD Graphics 620,No OS,1.86kg,575.00,Grande,Grande
3,4,Apple,MacBook Pro,Ultrabook,15.4,IPS Panel Retina Display 2880x1800,Intel Core i7 2.7GHz,16GB,512GB SSD,AMD Radeon Pro 455,macOS,1.83kg,2537.45,Grande,Grande
4,5,Apple,MacBook Pro,Ultrabook,13.3,IPS Panel Retina Display 2560x1600,Intel Core i5 3.1GHz,8GB,256GB SSD,Intel Iris Plus Graphics 650,macOS,1.37kg,1803.60,Pequeña,Mediana
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1298,1316,Lenovo,Yoga 500-14ISK,2 in 1 Convertible,14.0,IPS Panel Full HD / Touchscreen 1920x1080,Intel Core i7 6500U 2.5GHz,4GB,128GB SSD,Intel HD Graphics 520,Windows 10,1.8kg,638.00,Pequeña,Mediana
1299,1317,Lenovo,Yoga 900-13ISK,2 in 1 Convertible,13.3,IPS Panel Quad HD+ / Touchscreen 3200x1800,Intel Core i7 6500U 2.5GHz,16GB,512GB SSD,Intel HD Graphics 520,Windows 10,1.3kg,1499.00,Pequeña,Mediana
1300,1318,Lenovo,IdeaPad 100S-14IBR,Notebook,14.0,1366x768,Intel Celeron Dual Core N3050 1.6GHz,2GB,64GB Flash Storage,Intel HD Graphics,Windows 10,1.5kg,229.00,Pequeña,Mediana
1301,1319,HP,15-AC110nv (i7-6500U/6GB/1TB/Radeon,Notebook,15.6,1366x768,Intel Core i7 6500U 2.5GHz,6GB,1TB HDD,AMD Radeon R5 M330,Windows 10,2.19kg,764.00,Grande,Grande
1302,1320,Asus,X553SA-XX031T (N3050/4GB/500GB/W10),Notebook,15.6,1366x768,Intel Celeron Dual Core N3050 1.6GHz,4GB,500GB HDD,Intel HD Graphics,Windows 10,2.2kg,369.00,Grande,Grande

In [ ]:
df_computadores.value_counts('Medida Pantalla')

Medida Pantalla
Grande     835
Mediana    378
Pequeña     90
Name: count, dtype: int64

**Segunda Parte**

In [ ]:
df_fifa=pd.read_csv('/content/drive/MyDrive/CURSOS/Colab Notebooks/Python_2/fifa_ranking.csv', encoding='ISO-8859-1')
df_fifa.head(5)

,rank,country_full,country_abrv,total_points,previous_points,rank_change,cur_year_avg,cur_year_avg_weighted,last_year_avg,last_year_avg_weighted,two_year_ago_avg,two_year_ago_weighted,three_year_ago_avg,three_year_ago_weighted,confederation,rank_date
0,1,Germany,GER,0.0,57,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,UEFA,1993-08-08
1,2,Italy,ITA,0.0,57,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,UEFA,1993-08-08
2,3,Switzerland,SUI,0.0,50,9,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,UEFA,1993-08-08
3,4,Sweden,SWE,0.0,55,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,UEFA,1993-08-08
4,5,Argentina,ARG,0.0,51,5,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,CONMEBOL,1993-08-08

**Parte 1: Filtros simples**

In [ ]:
#Filtra y muestra los equipos que pertenecen a la confederación "CONMEBOL". ¿Cuántos equipos pertenecen a esta confederación?
df_fifa[df_fifa['confederation']=='CONMEBOL']

,rank,country_full,country_abrv,total_points,previous_points,rank_change,cur_year_avg,cur_year_avg_weighted,last_year_avg,last_year_avg_weighted,two_year_ago_avg,two_year_ago_weighted,three_year_ago_avg,three_year_ago_weighted,confederation,rank_date
4,5,Argentina,ARG,0.00,51,5,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,CONMEBOL,1993-08-08
7,8,Brazil,BRA,0.00,55,-5,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,CONMEBOL,1993-08-08
18,19,Colombia,COL,0.00,36,16,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,CONMEBOL,1993-08-08
21,22,Uruguay,URU,0.00,47,-6,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,CONMEBOL,1993-08-08
34,35,Ecuador,ECU,0.00,23,30,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,CONMEBOL,1993-08-08
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
57597,16,Colombia,COL,985.97,989,0,292.09,292.09,655.57,327.78,665.76,199.73,831.89,166.38,CONMEBOL,2018-06-07
57613,32,Paraguay,PAR,773.18,737,0,410.36,410.36,390.68,195.34,487.30,146.19,106.43,21.29,CONMEBOL,2018-06-07
57614,33,Venezuela,VEN,754.55,709,6,469.33,469.33,354.03,177.01,267.39,80.22,139.94,27.99,CONMEBOL,2018-06-07
57640,59,Bolivia,BOL,536.08,548,-2,291.14,291.14,313.86,156.93,222.28,66.68,106.60,21.32,CONMEBOL,2018-06-07
57641,60,Ecuador,ECU,523.85,506,3,67.14,67.14,387.50,193.75,630.02,189.01,369.77,73.95,CONMEBOL,2018-06-07

In [ ]:
df_fifa[df_fifa['confederation']=='CONMEBOL'].value_counts('confederation')

confederation
CONMEBOL    2860
Name: count, dtype: int64

In [ ]:
#Filtra y muestra información de los equipos "Germany" y "Argentina". Explica cómo usaste el filtro.
df_fifa[(df_fifa['country_full']== 'Germany') | (df_fifa['country_full']== 'Argentina')]

,rank,country_full,country_abrv,total_points,previous_points,rank_change,cur_year_avg,cur_year_avg_weighted,last_year_avg,last_year_avg_weighted,two_year_ago_avg,two_year_ago_weighted,three_year_ago_avg,three_year_ago_weighted,confederation,rank_date
0,1,Germany,GER,0.00,57,0,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,UEFA,1993-08-08
4,5,Argentina,ARG,0.00,51,5,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,CONMEBOL,1993-08-08
172,5,Germany,GER,0.00,57,-4,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,UEFA,1993-09-23
178,12,Argentina,ARG,0.00,56,-7,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,CONMEBOL,1993-09-23
337,4,Germany,GER,0.00,55,1,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,UEFA,1993-10-22
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
57164,5,Argentina,ARG,1253.61,1359,-1,418.94,418.94,839.74,419.87,769.42,230.83,919.87,183.97,CONMEBOL,2018-04-12
57371,1,Germany,GER,1543.99,1533,0,784.89,784.89,804.19,402.09,463.51,139.05,1089.77,217.95,UEFA,2018-05-17
57375,5,Argentina,ARG,1253.61,1254,0,418.94,418.94,839.74,419.87,769.42,230.83,919.87,183.97,CONMEBOL,2018-05-17
57582,1,Germany,GER,1558.49,1544,0,775.06,775.06,832.00,416.00,424.26,127.28,1200.77,240.15,UEFA,2018-06-07
57586,5,Argentina,ARG,1241.45,1254,0,404.07,404.07,809.59,404.80,829.98,248.99,917.94,183.59,CONMEBOL,2018-06-07

In [ ]:
#3.	Rangos de posiciones: Muestra los equipos que están en el top 10 del ranking. ¿Qué equipos aparecen?
df_fifa[df_fifa['rank']<= 10][['country_full', 'rank']]

      country_full  rank
0          Germany     1
1            Italy     2
2      Switzerland     3
3           Sweden     4
4        Argentina     5
...            ...   ...
57587  Switzerland     6
57588       France     7
57589       Poland     8
57590        Chile     9
57591        Spain    10

[2868 rows x 2 columns]

In [ ]:
#4.	Cambios positivos en el ranking: Filtra los equipos que tuvieron un cambio positivo en su posición ("rank_change" mayor a 0). ¿Cuántos equipos cumplen con esta condición?
len(df_fifa[df_fifa['rank_change']>0])

NameError: name 'df_fifa' is not defined

**Parte 2: Creación de columnas**

In [ ]:
#5.	Clasificación por puntaje: Crea una nueva columna llamada "Clasificación puntos" que categorice a los equipos según su "total_points":
#"Muy alto" si tienen más de 1500 puntos.
#"Alto" si tienen entre 1000 y 1500 puntos.
#"Moderado" si tienen entre 500 y 1000 puntos.
#"Bajo" si tienen menos de 500 puntos. ¿Cuántos equipos hay en cada categoría?
condiciones_2=[
    df_fifa['total_points']>1500,
    (df_fifa['total_points']>1000) & (df_fifa['total_points']<=1500),
    (df_fifa['total_points']>500) & (df_fifa['total_points']<= 1000),
    df_fifa['total_points']<= 500
]

valores_2=['Muy Alto', 'Alto', 'Moderado', 'Bajo']
df_fifa['Clasificación puntos']= np.select(condiciones_2, valores_2)
df_fifa.value_counts('Clasificación puntos')

Clasificación puntos
Bajo        52181
Moderado     4413
Alto         1104
Muy Alto       95
Name: count, dtype: int64

In [ ]:
#Niveles de promedio actual: Agrega una columna llamada "Nivel promedio actual" basada en "cur_year_avg":
#"Sobresaliente" si es mayor a 100.
#"Aceptable" si está entre 50 y 100.
#"Bajo" si es menor a 50. Realiza un conteo de cada nivel.
condiciones_3=[
    df_fifa['cur_year_avg']>100,
    (df_fifa['cur_year_avg']> 50) & (df_fifa['cur_year_avg']<=100),
    df_fifa['cur_year_avg']<= 50
]

valores_3=['Sobresaliente', 'Aceptable', 'Bajo']
df_fifa['Nivel promedio actual']= np.select(condiciones_3, valores_3)
df_fifa.head(5)

,rank,country_full,country_abrv,total_points,previous_points,rank_change,cur_year_avg,cur_year_avg_weighted,last_year_avg,last_year_avg_weighted,two_year_ago_avg,two_year_ago_weighted,three_year_ago_avg,three_year_ago_weighted,confederation,rank_date,Clasificación puntos,Nivel promedio actual
0,1,Germany,GER,0.0,57,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,UEFA,1993-08-08,Bajo,Bajo
1,2,Italy,ITA,0.0,57,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,UEFA,1993-08-08,Bajo,Bajo
2,3,Switzerland,SUI,0.0,50,9,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,UEFA,1993-08-08,Bajo,Bajo
3,4,Sweden,SWE,0.0,55,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,UEFA,1993-08-08,Bajo,Bajo
4,5,Argentina,ARG,0.0,51,5,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,CONMEBOL,1993-08-08,Bajo,Bajo

**Parte 3: Condiciones compuestas**

In [ ]:
#7.	Confederación y top 20: Filtra los equipos de la confederación "UEFA" que están dentro del top 20 del ranking. Muestra cuáles son y cuántos cumplen con ambas condiciones.
df_fifa[(df_fifa['confederation']=='UEFA') & (df_fifa['rank']<=20)]

,rank,country_full,country_abrv,total_points,previous_points,rank_change,cur_year_avg,cur_year_avg_weighted,last_year_avg,last_year_avg_weighted,two_year_ago_avg,two_year_ago_weighted,three_year_ago_avg,three_year_ago_weighted,confederation,rank_date,Clasificación puntos,Nivel promedio actual
0,1,Germany,GER,0.00,57,0,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,UEFA,1993-08-08,Bajo,Bajo
1,2,Italy,ITA,0.00,57,0,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,UEFA,1993-08-08,Bajo,Bajo
2,3,Switzerland,SUI,0.00,50,9,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,UEFA,1993-08-08,Bajo,Bajo
3,4,Sweden,SWE,0.00,55,0,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,UEFA,1993-08-08,Bajo,Bajo
5,6,Republic of Ireland,IRL,0.00,54,0,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,UEFA,1993-08-08,Bajo,Bajo
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
57594,12,England,ENG,1050.84,1040,1,476.42,476.42,593.51,296.75,580.49,174.15,517.60,103.52,UEFA,2018-06-07,Alto,Sobresaliente
57598,17,Netherlands,NED,980.98,969,2,545.74,545.74,299.13,149.56,333.54,100.06,928.10,185.62,UEFA,2018-06-07,Moderado,Sobresaliente
57599,18,Wales,WAL,953.46,931,3,335.47,335.47,745.20,372.60,359.92,107.98,687.06,137.41,UEFA,2018-06-07,Moderado,Sobresaliente
57600,19,Italy,ITA,951.25,947,1,341.93,341.93,732.11,366.05,415.76,124.73,592.70,118.54,UEFA,2018-06-07,Moderado,Sobresaliente
57601,20,Croatia,CRO,945.18,975,-2,397.75,397.75,672.78,336.39,335.96,100.79,551.26,110.25,UEFA,2018-06-07,Moderado,Sobresaliente

In [ ]:
df_fifa[(df_fifa['confederation']=='UEFA') & (df_fifa['rank']<=20)].value_counts('confederation')

confederation
UEFA    3808
Name: count, dtype: int64

In [ ]:
#8.	Cambios negativos o sin cambio: Encuentra los equipos que han tenido un cambio negativo o sin cambio ("rank_change" menor o igual a 0) y que pertenecen a la confederación "AFC". Indica cuántos equipos cumplen estas condiciones.
df_fifa[(df_fifa['rank_change']<=0) & (df_fifa['confederation']=='AFC')].value_counts('confederation')

confederation
AFC    8489
Name: count, dtype: int64

In [ ]:
#9.	Puntaje histórico alto: Filtra los equipos que tienen un "last_year_avg" mayor a 100 y "two_year_ago_avg" mayor a 100. ¿Cuántos equipos cumplen esta condición?
num_equipos_condicion = len(df_fifa[(df_fifa['last_year_avg'] > 100) & (df_fifa['two_year_ago_avg'] > 100)])
print(f"Número de equipos que cumplen la condición: {num_equipos_condicion}")

Número de equipos que cumplen la condición: 9188

**Parte 4: Uso de isin()**

In [ ]:
#10.	Equipos específicos con isin(): Usando la función isin(), filtra los equipos "Brazil", "Italy" y "France". Muestra su información completa.
df_fifa[df_fifa['country_full'].isin(['Brazil', 'Italy', 'France'])]

,rank,country_full,country_abrv,total_points,previous_points,rank_change,cur_year_avg,cur_year_avg_weighted,last_year_avg,last_year_avg_weighted,two_year_ago_avg,two_year_ago_weighted,three_year_ago_avg,three_year_ago_weighted,confederation,rank_date,Clasificación puntos,Nivel promedio actual
1,2,Italy,ITA,0.00,57,0,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,UEFA,1993-08-08,Bajo,Bajo
7,8,Brazil,BRA,0.00,55,-5,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,CONMEBOL,1993-08-08,Bajo,Bajo
11,12,France,FRA,0.00,45,7,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,UEFA,1993-08-08,Bajo,Bajo
167,1,Brazil,BRA,0.00,54,7,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,CONMEBOL,1993-09-23,Bajo,Bajo
168,2,Italy,ITA,0.00,56,0,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,UEFA,1993-09-23,Bajo,Bajo
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
57377,7,France,FRA,1166.42,1166,0,517.68,517.68,828.04,414.02,347.19,104.16,652.83,130.57,UEFA,2018-05-17,Alto,Sobresaliente
57390,20,Italy,ITA,947.03,947,0,373.61,373.61,692.51,346.25,411.89,123.57,518.05,103.61,UEFA,2018-05-17,Moderado,Sobresaliente
57583,2,Brazil,BRA,1430.57,1384,0,558.95,558.95,1082.36,541.18,560.21,168.06,811.88,162.38,CONMEBOL,2018-06-07,Alto,Sobresaliente
57588,7,France,FRA,1198.13,1166,0,520.12,520.12,856.75,428.38,393.65,118.09,657.68,131.54,UEFA,2018-06-07,Alto,Sobresaliente
57600,19,Italy,ITA,951.25,947,1,341.93,341.93,732.11,366.05,415.76,124.73,592.70,118.54,UEFA,2018-06-07,Moderado,Sobresaliente

In [ ]:
#11.	Confederaciones específicas: Filtra los equipos que pertenecen a las confederaciones "CONCACAF" o "CAF". ¿Cuántos equipos pertenecen a estas confederaciones?
df_fifa[df_fifa['confederation'].isin(['CONCACAF', 'CAF'])].value_counts('confederation')

confederation
CAF         14876
CONCACAF     9664
Name: count, dtype: int64

In [ ]:
#12.	Filtrado combinado: Usando isin(), filtra los equipos que pertenecen a "UEFA" y cuyo "rank" sea menor a 15. Muestra el resultado.
df_fifa[(df_fifa['confederation'].isin(['UEFA'])) & df_fifa['rank'].isin(range(1, 15))]

,rank,country_full,country_abrv,total_points,previous_points,rank_change,cur_year_avg,cur_year_avg_weighted,last_year_avg,last_year_avg_weighted,two_year_ago_avg,two_year_ago_weighted,three_year_ago_avg,three_year_ago_weighted,confederation,rank_date,Clasificación puntos,Nivel promedio actual
0,1,Germany,GER,0.00,57,0,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,UEFA,1993-08-08,Bajo,Bajo
1,2,Italy,ITA,0.00,57,0,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,UEFA,1993-08-08,Bajo,Bajo
2,3,Switzerland,SUI,0.00,50,9,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,UEFA,1993-08-08,Bajo,Bajo
3,4,Sweden,SWE,0.00,55,0,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,UEFA,1993-08-08,Bajo,Bajo
5,6,Republic of Ireland,IRL,0.00,54,0,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,UEFA,1993-08-08,Bajo,Bajo
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
57588,7,France,FRA,1198.13,1166,0,520.12,520.12,856.75,428.38,393.65,118.09,657.68,131.54,UEFA,2018-06-07,Alto,Sobresaliente
57589,8,Poland,POL,1182.61,1128,2,499.90,499.90,896.94,448.47,375.17,112.55,608.45,121.69,UEFA,2018-06-07,Alto,Sobresaliente
57591,10,Spain,ESP,1125.50,1162,-2,537.05,537.05,611.48,305.74,646.40,193.92,443.99,88.80,UEFA,2018-06-07,Alto,Sobresaliente
57593,12,Denmark,DEN,1051.44,1054,0,723.72,723.72,314.88,157.44,300.24,90.07,401.06,80.21,UEFA,2018-06-07,Alto,Sobresaliente
57594,12,England,ENG,1050.84,1040,1,476.42,476.42,593.51,296.75,580.49,174.15,517.60,103.52,UEFA,2018-06-07,Alto,Sobresaliente

**Parte 5: Ejercicios integradores**

In [ ]:
#13.	Análisis de top y cambios: Filtra los equipos que están en el top 50 y que han tenido un cambio de ranking positivo ("rank_change" > 0). Muestra el total de equipos que cumplen esta condición y realiza un conteo por confederación.
df_fifa[(df_fifa['rank']<=50) & (df_fifa['rank_change']>0)].value_counts('country_full')

country_full
Egypt                       104
Japan                       102
USA                         100
Romania                      95
Tunisia                      93
                           ...
Central African Republic      1
Cyprus                        1
Sierra Leone                  1
Guatemala                     1
El Salvador                   1
Name: count, Length: 110, dtype: int64

In [ ]:
#14.	Comparación de puntajes por año: Crea una nueva columna llamada "Puntaje histórico alto" que tenga el valor "Sí" si el "last_year_avg" es mayor que el "cur_year_avg"; en caso contrario, "No". ¿Cuántos equipos tuvieron un puntaje histórico más alto?
df_fifa['Puntaje histórico alto'] = np.where(df_fifa['last_year_avg'] > df_fifa['cur_year_avg'], 'Sí', 'No')
num_equipos_puntaje_alto = df_fifa['Puntaje histórico alto'].value_counts()['Sí']
print(f"Número de equipos con puntaje histórico alto: {num_equipos_puntaje_alto}")

Número de equipos con puntaje histórico alto: 7960

In [ ]:
#15.	Ranking y confederación: Filtra los equipos de la confederación "CONMEBOL" que están fuera del top 30. Crea una nueva columna que indique "En la cima" si el "rank" está entre los primeros 30 y "Rezagado" si no lo está. Realiza un conteo de cada categoría.
df_fifa[(df_fifa['confederation'] == 'CONMEBOL') & (df_fifa['rank'] > 30)]

,rank,country_full,country_abrv,total_points,previous_points,rank_change,cur_year_avg,cur_year_avg_weighted,last_year_avg,last_year_avg_weighted,two_year_ago_avg,two_year_ago_weighted,three_year_ago_avg,three_year_ago_weighted,confederation,rank_date,Clasificación puntos,Nivel promedio actual,Puntaje histórico alto,Ranking
34,35,Ecuador,ECU,0.00,23,30,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,CONMEBOL,1993-08-08,Bajo,Bajo,No,Rezagado
48,49,Chile,CHI,0.00,28,-2,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,CONMEBOL,1993-08-08,Bajo,Bajo,No,Rezagado
58,59,Bolivia,BOL,0.00,13,28,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,CONMEBOL,1993-08-08,Bajo,Bajo,No,Rezagado
66,67,Paraguay,PAR,0.00,22,1,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,CONMEBOL,1993-08-08,Bajo,Bajo,No,Rezagado
69,70,Peru,PER,0.00,16,8,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,CONMEBOL,1993-08-08,Bajo,Bajo,No,Rezagado
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
57433,63,Ecuador,ECU,506.42,506,1,67.14,67.14,372.42,186.21,626.79,188.04,325.19,65.04,CONMEBOL,2018-05-17,Moderado,Aceptable,Sí,Rezagado
57613,32,Paraguay,PAR,773.18,737,0,410.36,410.36,390.68,195.34,487.30,146.19,106.43,21.29,CONMEBOL,2018-06-07,Moderado,Sobresaliente,No,Rezagado
57614,33,Venezuela,VEN,754.55,709,6,469.33,469.33,354.03,177.01,267.39,80.22,139.94,27.99,CONMEBOL,2018-06-07,Moderado,Sobresaliente,No,Rezagado
57640,59,Bolivia,BOL,536.08,548,-2,291.14,291.14,313.86,156.93,222.28,66.68,106.60,21.32,CONMEBOL,2018-06-07,Moderado,Sobresaliente,Sí,Rezagado
57641,60,Ecuador,ECU,523.85,506,3,67.14,67.14,387.50,193.75,630.02,189.01,369.77,73.95,CONMEBOL,2018-06-07,Moderado,Aceptable,Sí,Rezagado

In [ ]:
df_fifa['Ranking'] = np.where(df_fifa['rank']<=30, 'En la cima', 'Rezagado')
df_fifa

,rank,country_full,country_abrv,total_points,previous_points,rank_change,cur_year_avg,cur_year_avg_weighted,last_year_avg,last_year_avg_weighted,two_year_ago_avg,two_year_ago_weighted,three_year_ago_avg,three_year_ago_weighted,confederation,rank_date,Clasificación puntos,Nivel promedio actual,Puntaje histórico alto,Ranking
0,1,Germany,GER,0.0,57,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,UEFA,1993-08-08,Bajo,Bajo,No,En la cima
1,2,Italy,ITA,0.0,57,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,UEFA,1993-08-08,Bajo,Bajo,No,En la cima
2,3,Switzerland,SUI,0.0,50,9,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,UEFA,1993-08-08,Bajo,Bajo,No,En la cima
3,4,Sweden,SWE,0.0,55,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,UEFA,1993-08-08,Bajo,Bajo,No,En la cima
4,5,Argentina,ARG,0.0,51,5,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,CONMEBOL,1993-08-08,Bajo,Bajo,No,En la cima
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
57788,206,Anguilla,AIA,0.0,0,1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,CONCACAF,2018-06-07,Bajo,Bajo,No,Rezagado
57789,206,Bahamas,BAH,0.0,0,1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,CONCACAF,2018-06-07,Bajo,Bajo,No,Rezagado
57790,206,Eritrea,ERI,0.0,0,1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,CAF,2018-06-07,Bajo,Bajo,No,Rezagado
57791,206,Somalia,SOM,0.0,0,1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,CAF,2018-06-07,Bajo,Bajo,No,Rezagado
57792,206,Tonga,TGA,0.0,0,1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,OFC,2018-06-07,Bajo,Bajo,No,Rezagado